import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import { ModeToggle } from "@/components/mode-toggle";
import { ReactNode } from "react";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <title>Seoyeon Blogs</title>
      <meta name="description" content="Frontend Developer Seoyeon's Blog" />
      <meta name="keywords" content="Frontend, Developer, Blog, Seoyeon" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="Seoyeon Blog" />
      <meta property="og:description" content="Frontend Developer Seoyeon's Blog" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://seoyeon-next-blog-uw4w.vercel.app/" />
      <meta property="og:image" content="/seoyeon-blog-meta-image.png" />
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-2xl mx-auto py-10 px-4">
            <header>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Image
                    src="/seoyeon-blog-icon.png"
                    alt="seoyeon-blog-icon"
                    width={40}
                    height={40}
                    className={"rounded-full border-2 border-slate-300"}
                  />
                  <span className="font-bold text-lg text-slate-800 dark:text-slate-200">
                    Seoyeon Blog
                  </span>
                </div>
                <nav className="ml-auto text-sm font-medium space-x-6 flex items-center">
                  <Link href="/">Home</Link>
                  <Link href="/about">About</Link>
                  <ModeToggle />
                </nav>
              </div>
            </header>
            <main>{children}</main>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
